connection: &connection
  adapter: postgresql
  host: localhost
  pool: 5
  timeout: 5000
  min_messages: warning
  username: postgres
  password: lol

development:
  <<: *connection
  database: edgar_development

test: &test
  <<: *connection
  database: edgar_test

cucumber:
  <<: *test
